Fix flaky test qp_misc_jiras
qp_misc_jiras access view "pg_partitions" internal which cannot run concurrently
with queries which drop a partition table. View "pg_partitions" contains a
simple pattern: select pg_get_expr(xxxxx, 'partition_oid') from pg_partition_rule;
so if a partition table is dropped between its oid been scanned from pg_partition_rule
and opened by pg_get_expr() for first time, the error as below will report.
  ERROR:  relation not found (OID 130643)
  DETAIL:  This can be validly caused by a concurrent delete operation
  on this object.

The behave of error is same with upstream, so the fix is to run qp_misc_jiras
serially with others.

Co-authored-by: Wu Hao hawu@pivotal.io