Adjust lock levels in DROP RESOURCE GROUP and gp_resource_status;
Below case would fail before:

    tx1: BEGIN;
    tx1: DROP RESOURCE GROUP g1;

    tx2: SELECT * FROM gp_toolkit.gp_resource_status;
    ERROR:  Cannot find resource group with Oid 131080 in shared memory

Fixed by make DROP RESOURCE conflict with gp_resource_status;